import type { Metadata } from "next";
import {
  Alkatra,
  Istok_Web,
  Nothing_You_Could_Do,
  Poppins,
  Prosto_One,
  Rajdhani,
} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});
const nothingYouCouldDo = Nothing_You_Could_Do({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-nothing-you-could-do",
});
const prostoOne = Prosto_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-prosto",
});

const alkatra = Alkatra({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-alatra",
});
const istok = Istok_Web({
  weight:["400", "700"],
  subsets:["latin"],
  variable:'--font-istok-web'
})
const rajdhani = Rajdhani({
  weight:["300", "400", "500", "600", "700"],
  subsets:["latin"],
  variable:'--font-rajdhani'
})


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pro Study Mate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${istok.variable} ${prostoOne.variable} ${nothingYouCouldDo.variable} ${rajdhani.variable} ${alkatra.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
